spring:
  application:
    name: school-system
  datasource:
    url: jdbc:mysql://localhost:3306/school_db?
    username: root
    password: yourpassword
  jpa:
    show-sql: true
    ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 1200 # 5min
    refreshTokenExpiration: 604800 # 7days

